### ISSUE TITLE
Auskommentierte Funktionen löschen

### ISSUE THREAD

**Issue by lforsthuber05** [4ahmns-MTIN-2223-WiSem/05VDuernberger-Recap#2]
In dem Manager.cs-Script ist eine Funktion auskommentiert, die somit gelöscht werden könnte.

**Comment by vduernberger** [comment]
Habe die Funktion nicht weggelöscht, da ich in zukünftigen Projekten darauf zurückblicken kann und das vielleicht gebrauchen könnte. Aber dankeschön!
